# Generated by Django 5.1.6 on 2025-05-28 18:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerereClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_client', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('detalii_produs', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('data_cerere', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
                ('nr_telefon', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('descriere', models.CharField(max_length=255)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.client')),
            ],
        ),
        migrations.CreateModel(
            name='ContFurnizor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_tranzactie', models.CharField(choices=[(1, 'Debit'), (2, 'Credit')], max_length=255)),
                ('suma_tranzactie', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_tranzactie', models.DateField()),
                ('modalitate_plata', models.CharField(max_length=255)),
                ('id_furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='BancaFurnizor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_cont_bancar', models.CharField(max_length=255)),
                ('swift', models.CharField(max_length=255)),
                ('id_furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('tip_produs', models.CharField(max_length=255)),
                ('pret_cumparare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_vanzare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_produs', models.DecimalField(decimal_places=2, help_text='Procentaj TVA, de ex. 19.00 pentru 19%', max_digits=5)),
                ('nr_lot', models.CharField(max_length=255)),
                ('nr_raft', models.CharField(max_length=255)),
                ('data_expirare', models.DateField()),
                ('data_producere', models.DateField()),
                ('descriere', models.CharField(max_length=255)),
                ('stoc_total', models.IntegerField()),
                ('cantitate_in_pachet', models.IntegerField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiProdus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_atribut', models.CharField(max_length=255)),
                ('valoare_atribut', models.CharField(max_length=255)),
                ('unitate_masura', models.CharField(blank=True, max_length=255, null=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('descriere', models.CharField(blank=True, max_length=255, null=True)),
                ('id_produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.produs')),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantitate', models.IntegerField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.factura')),
                ('id_produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('este_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SalariuAngajat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_salariu', models.DateField()),
                ('suma_salariu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BancaAngajat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_cont_bancar', models.CharField(max_length=255)),
                ('swift', models.CharField(max_length=255)),
                ('id_angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
