# Generated by Django 5.1.6 on 2025-05-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0003_alter_furnizor_data_adaugare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angajat',
            name='functie',
        ),
    ]
