# Generated by Django 5.1.6 on 2025-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0006_rename_adresa_angajat_prenume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='parola',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='angajat',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
