# Generated by Django 5.1.6 on 2025-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0008_alter_angajat_options_alter_angajat_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contfurnizor',
            name='suma_tranzactie',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='produs',
            name='pret_cumparare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produs',
            name='pret_vanzare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produs',
            name='tva_produs',
            field=models.DecimalField(decimal_places=2, help_text='Procentaj TVA, de ex. 19.00 pentru 19%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salariuangajat',
            name='suma_salariu',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
