# Generated by Django 5.1.6 on 2025-05-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0009_alter_contfurnizor_suma_tranzactie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
