# Generated by Django 5.1.6 on 2025-02-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('parola', models.CharField(max_length=255)),
                ('ultima_autentificare', models.DateTimeField(auto_now=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('functie', models.CharField(max_length=255)),
                ('data_angajare', models.DateField()),
                ('telefon', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CerereClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_client', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('detalii_produs', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('data_cerere', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
                ('nr_telefon', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('descriere', models.CharField(max_length=255)),
                ('data_adaugare', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BancaAngajat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_cont_bancar', models.CharField(max_length=255)),
                ('swift', models.CharField(max_length=255)),
                ('id_angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.angajat')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.client')),
            ],
        ),
        migrations.CreateModel(
            name='ContFurnizor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_tranzactie', models.CharField(choices=[(1, 'Debit'), (2, 'Credit')], max_length=255)),
                ('suma_tranzactie', models.IntegerField()),
                ('data_tranzactie', models.DateField()),
                ('modalitate_plata', models.CharField(max_length=255)),
                ('id_furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='BancaFurnizor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_cont_bancar', models.CharField(max_length=255)),
                ('swift', models.CharField(max_length=255)),
                ('id_furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('tip_produs', models.CharField(max_length=255)),
                ('pret_cumparare', models.IntegerField()),
                ('pret_vanzare', models.IntegerField()),
                ('taxa_cumparare', models.IntegerField()),
                ('taxa_vanzare', models.IntegerField()),
                ('nr_lot', models.CharField(max_length=255)),
                ('nr_raft', models.CharField(max_length=255)),
                ('data_expirare', models.DateField()),
                ('data_producere', models.DateField()),
                ('descriere', models.CharField(max_length=255)),
                ('stoc_total', models.IntegerField()),
                ('cantitate_in_pachet', models.IntegerField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiProdus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_ingredient', models.CharField(max_length=255)),
                ('cantitate_ingredient', models.IntegerField()),
                ('tip_cantitate_ingredient', models.CharField(max_length=255)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('descriere', models.CharField(max_length=255)),
                ('id_produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.produs')),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantitate', models.IntegerField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.factura')),
                ('id_produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.produs')),
            ],
        ),
        migrations.CreateModel(
            name='SalariuAngajat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_salariu', models.DateField()),
                ('suma_salariu', models.IntegerField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('id_angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemManagementInventar.angajat')),
            ],
        ),
    ]
