# Generated by Django 5.1.6 on 2025-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detaliiprodus',
            old_name='nume_ingredient',
            new_name='nume_atribut',
        ),
        migrations.RenameField(
            model_name='detaliiprodus',
            old_name='tip_cantitate_ingredient',
            new_name='valoare_atribut',
        ),
        migrations.RemoveField(
            model_name='detaliiprodus',
            name='cantitate_ingredient',
        ),
        migrations.AddField(
            model_name='detaliiprodus',
            name='unitate_masura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detaliiprodus',
            name='descriere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
