# Generated by Django 5.1.6 on 2025-04-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0002_rename_nume_ingredient_detaliiprodus_nume_atribut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnizor',
            name='data_adaugare',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
