# Generated by Django 5.1.6 on 2025-05-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0004_remove_angajat_functie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produs',
            old_name='taxa_cumparare',
            new_name='tva_produs',
        ),
        migrations.RemoveField(
            model_name='produs',
            name='taxa_vanzare',
        ),
    ]
