# Generated by Django 5.1.6 on 2025-05-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemManagementInventar', '0005_rename_taxa_cumparare_produs_tva_produs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angajat',
            old_name='adresa',
            new_name='prenume',
        ),
        migrations.RemoveField(
            model_name='angajat',
            name='data_adaugare',
        ),
        migrations.RemoveField(
            model_name='angajat',
            name='data_angajare',
        ),
        migrations.AddField(
            model_name='angajat',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='angajat',
            name='este_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='angajat',
            name='parola',
            field=models.CharField(default='default_password', max_length=255),
        ),
        migrations.AddField(
            model_name='angajat',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='angajat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='angajat',
            name='telefon',
            field=models.CharField(max_length=20),
        ),
    ]
